### ISSUE TITLE
프로젝트 초기 환경 세팅

### ISSUE THREAD

**Issue by bbearcookie** [team-moabam/moabam-FE#1]
# ⚙️ Setting
## Description
프로젝트의 초기 환경을 설정할 계획이에요.

## To-do
- [x] type alias 설정
- [x] eslint, prettier 설정
- [x] husky, lint-staged 및 pre-commit 규칙 설정
- [x] commitlint 로 커밋 메시지 규칙 설정
- [x] react-hook-form, zod 설치
- [x] axios, tanstack-query 설치 및 설정
- [x] zustand 설치
- [x] tailwind-css 설치 및 설정
- [x] react-router-dom 설치 및 설정
- [x] react-error-boundary 설치
- [x] eslint-plugin-import 로 import 순서 정리 (#2)
- [x] storybook 설치 및 설정
- [x] react-icons 설치
- [x] querykey-factory 설치 (https://github.com/orgs/team-moabam/discussions/2)
