### ISSUE TITLE
쿠폰 관련 페이지 작성

### ISSUE THREAD

**Issue by chasj0326** [team-moabam/moabam-FE#140]
# ✨ Feature
## Description
쿠폰 관련한 UI 들을 작성합니다

## To-do
- [ ] 메인페이지(루틴페이지)에 쿠폰 배너 추가
- [ ] 쿠폰 이벤트 페이지 작성
- [ ] 팝업 > 쿠폰 이벤트 페이지 구현
- [ ] 배너 > 쿠폰 이벤트 페이지 구현
