### ISSUE TITLE
서비스 워커 관련 이슈 해결

### ISSUE THREAD

**Issue by bbearcookie** [team-moabam/moabam-FE#158]
# 🚨 Hotfix
## Description
현재 MSW 환경에서 실행시 Vite PWA로 등록한 서비스 워커와 겹쳐서 발생하는 문제를 해결해야 해요.

## To-do
- [ ] 개발 서버에서는 MSW의 서비스 워커만 사용하도록 작업.
- [ ] FCM 메시지를 수신할 수 있는 서비스 워커 생성.
- [ ] PWA와 관련한 애셋 폴더 정리
