### ISSUE TITLE
상세페이지 사소한 기능들 수정

### ISSUE THREAD

**Issue by nayeon-hub** [team-moabam/moabam-FE#306]
# 🚨 Hotfix
## ToDo
- [ ] 상세 페이지 헤더에서 방장만 방 수정 페이지 이동버튼 보이기
- [ ] sleepImage, awakeImage 데이터 적용하기
- [ ] 데이터 적용안된 부분 적용
