### ISSUE TITLE
상세페이지 1차 오류 수정

### ISSUE THREAD

**Issue by nayeon-hub** [team-moabam/moabam-FE#333]
# 🚨 Hotfix
## Description
현재 어떤 버그가 있는지 작성해주세요. 이미지를 첨부하셔도 좋습니다.

## To-do
- [ ] 수정 버튼 방장한테 보이기
- [ ] 콕찔렀을 때, 토스트 띄우기
- [ ] 콕찔렀을 때, 낙관적 업데이트
- [ ] 인증시간 수정
- [ ] 신고하기 전달 데이터 string으로 변환
- [x] 방 가입 에러 발생 시 에러 토스트 띄우기
- [ ] 방 나갈 시 토스트 띄우기
- [ ] 인증 시간 끝났을 때, 모달 지우기
