### ISSUE TITLE
상세페이지 3차 수정

### ISSUE THREAD

**Issue by nayeon-hub** [team-moabam/moabam-FE#365]
# 🚨 Hotfix

## To-do
- [x] 콕 찌르기 에러 토스트 띄우기
- [x] 방 인원수에 아이콘 추가
- [x] 인증 사진 전송
