### ISSUE TITLE
Web Push 관련 리팩토링

### ISSUE THREAD

**Issue by bbearcookie** [team-moabam/moabam-FE#368]
# ♻️ Refactor
## Description
Web Push 관련 리팩토링

## To-do
- [ ] 카카오 로그인 redirect 페이지의 리렌더링을 방지하고자 `useLocalStorage` 훅 제거
- [ ] 알림 끈 상태에서 로그인한 뒤에 알림을 허용하면 토큰 전송 API가 두 번 호출되는 문제 수정
- [ ] Web Push 메시지 클릭 시 모아밤 켜지도록 작업
