### ISSUE TITLE
인증 시간 오류 수정

### ISSUE THREAD

**Issue by nayeon-hub** [team-moabam/moabam-FE#382]
# 🚨 Hotfix
## Description
현재 어떤 버그가 있는지 작성해주세요. 이미지를 첨부하셔도 좋습니다.

## To-do
- [ ]  밤 11시쯤 인증시간 제한 수정하기
- [ ] 방 생성시 그 전 기록 보지 못하도록 해야할 것 같네용
- [x] 캘린더 클릭 시 스타일 수정하기
- [x] 이미지 업로드 시 타입 지정하기
- [x] 인증하기 버튼 텍스트 수정하기
