### ISSUE TITLE
방 상세 벌레 획득 정보 UI 추가

### ISSUE THREAD

**Issue by chasj0326** [team-moabam/moabam-FE#428]
# ✨ Feature
## Description
방 상세에서 맡은 일들을 할 예정이에요 !

## To-do
- [x] 벌레 획득 정보 UI 추가
- [x] 공지 UI 수정
- [x] 스토리지 저장 로직 수정
