### ISSUE TITLE
시간 기반 테마 설정 및 DOM 트리 구조 정리

### ISSUE THREAD

**Issue by bbearcookie** [team-moabam/moabam-FE#57]
# ✨ Feature
## Description
createPortal를 위한 트리 구조를 정리하고, 시간 기반으로 테마를 주입하는 기능을 작성할 계획이에요.

## To-do
- [ ] 시간 기반 테마 지정 Context 작성
- [x] DOM 트리 구조 정리
- [x] 전역 font 설정
