### ISSUE TITLE
RoomNew 페이지 로직 작성

### ISSUE THREAD

**Issue by bbearcookie** [team-moabam/moabam-FE#67]
# ✨ Feature
## Description
실제로 동작하는 RoomNew 페이지 로직 작성
(작업하다보니 코드 규모가 커져서 여러 PR로 나눠서 올릴게요!)

## To-do
- [x] TimePicker props 이름 변경 및 formatHourString 함수 작성
- [x] 스타일, 유효성 스키마 등 상수 정리
- [x] 실제로 동작하는 RoomNew 페이지 로직 작성

## 만든 결과물
https://github.com/team-moabam/moabam-FE/assets/50488780/5c304b0f-bfd5-458f-a6c1-8147b8ee4a43
