### ISSUE TITLE
방 생성 페이지 API 로직 작성

### ISSUE THREAD

**Issue by bbearcookie** [team-moabam/moabam-FE#90]
# ✨ Feature
## Description
방 생성 페이지에 API 호출하는 기능을 작업할 계획이에요.

## To-do
- [ ] `POST /rooms` 요청 함수 작성
- [ ] `POST /rooms` 모킹 함수 작성
- [ ] `useMutation()` 훅으로 API 요청 로직 작성
