### ISSUE TITLE
루틴 목록 페이지 UI 작성

### ISSUE THREAD

**Issue by chasj0326** [team-moabam/moabam-FE#96]
# ✨ Feature
## Description
루틴 목록 페이지 UI 를 작성합니다.

## To-do
- [ ] 현재 시간 가져오기 (임시!!)
  - [ ] mockData 에서 아침 / 밤 나누어서 시간대에 맞게 보여주기
  - [ ] 슬라이드 전환 기능
